/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /mnt/home/universalpackagemanager/UPM/perl-5.26.1/miniperl ../bin/enc2xs -Q -o ma_03_t.c -f ma_03_t.fnm
 enc2xs VERSION 2.20
*/
extern encode_t MacChineseTrad_encoding;
