#ifndef PANGO_FEATURES_H
#define PANGO_FEATURES_H

#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 40
#define PANGO_VERSION_MICRO 13

#define PANGO_VERSION_STRING "1.40.13"

#endif /* PANGO_FEATURES_H */
