/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /mnt/home/universalpackagemanager/UPM/perl-5.26.1/miniperl ../bin/enc2xs -Q -o ir_04_t.c -f ir_04_t.fnm
 enc2xs VERSION 2.20
*/
extern encode_t iso_ir_165_encoding;
